In [1]:
import pandas as pd

In [2]:
data_path = '../data/final_dataset.csv'

In [3]:
data = pd.read_csv(data_path)

In [4]:
data.drop(data[(data['premium_purchased_next_month'] == 1) & (
    data['premium_purchased_this_month'] == 1)].index, inplace=True)

In [5]:
data[(data['premium_purchased_next_month'] == 1) &
     (data['premium_purchased_this_month'] == 1)]

Empty DataFrame
Columns: [name, city, street, favourite_genres, user_id, year, month, number_of_advertisements, number_of_skips, number_of_likes, total_tracks_duration_ms, number_of_different_artists, average_release_date, average_duration_ms, explicit_tracks_ratio, average_popularity, average_acousticness, average_danceability, average_energy, average_instrumentalness, average_liveness, average_loudness, average_speechiness, average_tempo, average_valence, premium_purchased, premium_purchased_this_month, premium_purchased_next_month]
Index: []

[0 rows x 28 columns]

In [6]:
grouped_data = data.groupby('user_id')

user_tables = {}
for user_id, group in grouped_data:
    user_tables[user_id] = group.copy()

In [7]:
user_df = user_tables[261]
user_df

,name,city,street,favourite_genres,user_id,year,month,number_of_advertisements,number_of_skips,number_of_likes,...,average_energy,average_instrumentalness,average_liveness,average_loudness,average_speechiness,average_tempo,average_valence,premium_purchased,premium_purchased_this_month,premium_purchased_next_month
1161,Kornelia Rosłoń,Warszawa,al. Jana 757,"[""latin pop"", ""mellow gold"", ""new wave pop""]",261,2023,1,5,15,8,...,0.734155,0.102597,0.213791,-8.140364,0.054355,130.211455,0.560333,0,0,0
1162,Kornelia Rosłoń,Warszawa,al. Jana 757,"[""latin pop"", ""mellow gold"", ""new wave pop""]",261,2023,6,15,28,13,...,0.680665,0.087579,0.237327,-8.677784,0.074251,125.281980,0.532059,0,0,0
1163,Kornelia Rosłoń,Warszawa,al. Jana 757,"[""latin pop"", ""mellow gold"", ""new wave pop""]",261,2023,8,12,20,16,...,0.583850,0.063614,0.223845,-10.303600,0.041250,122.250200,0.524982,0,0,0
1164,Kornelia Rosłoń,Warszawa,al. Jana 757,"[""latin pop"", ""mellow gold"", ""new wave pop""]",261,2023,10,10,19,10,...,0.663897,0.165483,0.245997,-9.564167,0.062330,131.125267,0.476823,0,0,0

In [8]:
new_table = []
for user_df in user_tables.values():
    condition = user_df['premium_purchased_this_month'] == 1
    filtered_df = user_df[condition]
    try:
        month = filtered_df['month'].iloc[0]
    except Exception:
        month = 12
    new_table.append(user_df[user_df['month'] <= month])

In [9]:
merged_data = pd.concat(new_table, ignore_index=True)

In [10]:
merged_data

,name,city,street,favourite_genres,user_id,year,month,number_of_advertisements,number_of_skips,number_of_likes,...,average_energy,average_instrumentalness,average_liveness,average_loudness,average_speechiness,average_tempo,average_valence,premium_purchased,premium_purchased_this_month,premium_purchased_next_month
0,Maurycy Lejk,Wrocław,al. Powstańców Śląskich 04,"[""regional mexican"", ""blues rock"", ""dance pop""]",101,2023,1,8,28,11,...,0.686078,0.138835,0.200741,-8.702667,0.063267,132.429784,0.551457,0,0,0
1,Maurycy Lejk,Wrocław,al. Powstańców Śląskich 04,"[""regional mexican"", ""blues rock"", ""dance pop""]",101,2023,4,1,5,4,...,0.781750,0.042087,0.242212,-6.816750,0.055700,113.688375,0.509212,0,0,0
2,Maurycy Lejk,Wrocław,al. Powstańców Śląskich 04,"[""regional mexican"", ""blues rock"", ""dance pop""]",101,2023,5,16,12,12,...,0.680166,0.136585,0.242509,-9.053219,0.063556,124.215812,0.522266,0,0,0
3,Maurycy Lejk,Wrocław,al. Powstańców Śląskich 04,"[""regional mexican"", ""blues rock"", ""dance pop""]",101,2023,6,14,16,12,...,0.623364,0.124840,0.264388,-9.923273,0.055442,118.929879,0.444758,0,0,0
4,Maurycy Lejk,Wrocław,al. Powstańców Śląskich 04,"[""regional mexican"", ""blues rock"", ""dance pop""]",101,2023,9,9,15,8,...,0.702167,0.047936,0.252671,-8.793958,0.054192,118.411292,0.529125,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118456,Gustaw Kiljan,Poznań,aleja Solidarnosci 96,"[""dance pop"", ""soul"", ""latin""]",20100,2023,5,14,2,13,...,0.606892,0.044203,0.188727,-7.216243,0.082197,116.639622,0.480070,1,0,0
118457,Gustaw Kiljan,Poznań,aleja Solidarnosci 96,"[""dance pop"", ""soul"", ""latin""]",20100,2023,6,16,4,17,...,0.632027,0.018852,0.191423,-6.438000,0.081286,115.419877,0.535247,1,0,0
118458,Gustaw Kiljan,Poznań,aleja Solidarnosci 96,"[""dance pop"", ""soul"", ""latin""]",20100,2023,7,11,0,5,...,0.597839,0.043246,0.182500,-6.762871,0.087197,119.483581,0.518658,1,0,0
118459,Gustaw Kiljan,Poznań,aleja Solidarnosci 96,"[""dance pop"", ""soul"", ""latin""]",20100,2023,7,11,0,5,...,0.597839,0.043246,0.182500,-6.762871,0.087197,119.483581,0.518658,1,0,1
118460,Gustaw Kiljan,Poznań,aleja Solidarnosci 96,"[""dance pop"", ""soul"", ""latin""]",20100,2023,8,29,6,19,...,0.635667,0.010941,0.142990,-6.050321,0.080446,118.112940,0.504238,1,1,0

In [11]:
merged_data.to_csv("../data/final_data_filtered.csv")